### PR TITLE
Added delete, edit and add functionality for success stories

### PR DESCRIPTION
**Pull request by JennaDalgety**
Added delete, edit and add success story functionality to back-end.

### CODE REVIEW

**Comment by allyson09** [comment]
Cool beans! Just take out your puts and and comment and you're good to go!

**Comment by allyson09** [comment]
Looks good!

**Review by allyson09 — APPROVED** [review]
Looks good! Just take out your comment :)

**Review by spyeadon — COMMENTED** [review]
looks great to me!

**Pull request merged**
