### PR TITLE
FAQ edit, add, delete functionality; no validations

### PR DESCRIPTION
**Pull request by JennaDalgety**
Methods for adding a new faq, editing an faq and deleting an faq.

Initial tests show these methods working, so *fingers crossed* no bugs!

### CODE REVIEW

**Comment by zachgarwood** [comment]
Looks good to me 🐲 

@spyeadon & @allyson09 please take a quick minute to review, leave a comment if necessary, or give it the okay!

**Comment by spyeadon** [comment]
Looks good to me as well! @JennaDalgety @zachgarwood @allyson09

**Comment by allyson09** [comment]
Looks great! Huzzaaaaaah! 💃 💃 💃

**Review by spyeadon — APPROVED** [review]
Looks good

**Comment by zachgarwood** [comment]
@allyson09 don't forget to do a formal review using the **Add your review button**!

**Review by allyson09 — APPROVED** [review]
It looks super nice! 🕺 🕺 🕺

**Pull request merged**
